### ISSUE TITLE
Wrong size of `QP_versionStr[]` in declaration

### ISSUE THREAD

**Issue by esolosh** [QuantumLeaps/qpn#4]
In definition (qepn.c) the size is 7:  
```
char_t const Q_ROM QP_versionStr[7] = QP_VERSION_STR;
```

while in declaration (qepn.h) it is 6:  
```
extern char_t const Q_ROM QP_versionStr[6];
```

**Comment by quantum-leaps** [comment]
Thanks for pointing this out. The issue has been corrected.
--MMS

**Comment by esolosh** [comment]
Thanks for the fast fix.

**Comment by jwinarske** [comment]
What commit has this fix?

**Comment by quantum-leaps** [comment]
QP-nano 6.5.0 commit b8da3c4, see:

https://github.com/QuantumLeaps/qpn/blob/fbab8d11d72505df084248012eb09cfe54f86026/include/qepn.h#L436

**Comment by jwinarske** [comment]
thanks!
