### ISSUE TITLE
Supporting targets with 16-bit bytes

### ISSUE THREAD

**Issue by bikeNomad** [QuantumLeaps/qpn#5]
I am considering using qpn for a product I'm working on. We're using the TI C2000 (Delfino) family processors, which don't have byte addressing. So there's no `uint8_t`, and `sizeof(char) == sizeof(int16_t)`.
I see that qpn uses `uint8_t` in its code.
In my code, I've had to change references to `uint8_t` to `uint_least8_t`.

**Comment by quantum-leaps** [comment]
Hi Ned,
Before doing your port, you might want to see the "Legacy QDK" for the TI C2000, available at:

https://sourceforge.net/projects/qpc/files/legacy-QDKs/qdkc_tms320c28x-c2000_4.5.03.zip/download

This ZIP file contains documentation of the port in PDF.

Good luck,
Miro

**Comment by tinix84** [comment]
I was trying to do something similar then I checkout git://git.code.sf.net/u/arauto/qpc and I have tried to compile the examples project dpp but I get linker problem:
![image](https://user-images.githubusercontent.com/16301528/76645402-38f07980-6559-11ea-90bc-a7f96c55970d.png)
Do you have any idea why?
Is it the fact I'm using a different compiler?
![image](https://user-images.githubusercontent.com/16301528/76645489-60474680-6559-11ea-9e6f-343c5fe6c4b1.png)
Thanks
Riccardo

**Comment by quantum-leaps** [comment]
Hi Ricardo,
This must be some older QP/C version for the C28 DSPs. Back in those days, QP/C was deployed as a library, which is apparently missing in your case (your `qp2800_ml.lib`). This QP/C library must be then built separately before you can link it into your applications. I believe that the QDK Manual for the C28 DPSs should describe how to build the library.
--MMS
