### ISSUE TITLE
why don't have trasplant example of 8051?

### ISSUE THREAD

**Issue by ywei321** [QuantumLeaps/qpn#6]
why don't have trasplant example of 8051?
I don't find an example of 8051.Is there any problem or other reason?
How to transplant?
thank you very much!

**Comment by quantum-leaps** [comment]
The [8051 CPU has been supported in the past](https://www.drdobbs.com/architecture-and-design/uml-statecharts-at-1099/188101799), but the support has been dropped. The old and outdated CPU architectures (like 8051, PIC10/12/16, etc.) predate the use of the C programming language and were really not designed for it. Consequently, any C-language implementations for these CPUs are non-portable and require many non-standard extensions to the language. Any such extensions are non-portable and contaminate the source code. For these reasons the outdated CPUs are no longer supported.

Finally, please also note that the QP-nano framework itself is no longer actively developed and is not recommended for new designs.

--MMS

**Comment by ywei321** [comment]
I am a MCU engineer.Does it mean that 8051 can't apply this kind of architecture.What a pity！
Anyway, thank you for your reply。

**Comment by ywei321** [comment]
I downloaded the example in the link you gave, but the file is incomplete. Is there a complete file download? thank you

**Comment by ywei321** [comment]
I have ported it to the 8051 MCU, but the ROM usage is up to 6867 bytes.There are three questions: 
First:is there any way to reduce THE ROM occupancy?
Second: is there a case reference for the KEil compiler?
Third:is it possible to reduce the code footprint to below 4K bytes as you said?
I really admire what you've done, so I want to learn from you.thank you very much!

**Comment by quantum-leaps** [comment]
You might want to compare your port with the existing "legacy-QDK" (QP Development Kit) for 8051 ( qdkn_8051-iar_4.0.02.zip), still available from https://sourceforge.net/projects/qpc/files/legacy-QDKs . Otherwise the 8051 is really an anachronism from a different era. It is not recommended for any QP frameworks. 
--MMS

**Comment by ywei321** [comment]
Thank you very much for your timely reply. Due to my current job, I want to learn such knowledge, which is also a preparation for the transplant of other platforms in the future.
